### ISSUE TITLE
./Formats/scanitemmodel.cpp contains a wrong positioned if condition 

### ISSUE THREAD

**Issue by otavioarj** [horsicq/Formats#6]
I appears that the condition: `435: if (g_bIsColoredOutput) {` was wrongly positioned inside the `431: #ifdef Q_OS_WIN` , having its scope broke by the `505: #endif`. Resulting the the following compiler errors:

> ../Formats/scanitemmodel.cpp:508:11: error: expected constructor, destructor, or type conversion before ‘(’ token
  508 |     printf("%s", pItem->data(0).toString().toUtf8().data());
      |           ^
../Formats/scanitemmodel.cpp:510:5: error: expected unqualified-id before ‘if’
  510 |     if (g_bIsColoredOutput) {
      |     ^~
../Formats/scanitemmodel.cpp:524:1: error: expected declaration before ‘}’ token
  524 | }
      | ^

Placing the  `if (g_bIsColoredOutput) {`  just above the  `#ifdef Q_OS_WIN` solved the compiler error and resulted in the correct build of the executable.

Env:
>$ g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by horsicq** [comment]
Thanks a lot! 
Fixed: https://github.com/horsicq/Formats/commit/6df50f5eb7fa81977143135a95507583bbd859f5
